spring:
  application:
    name: BusinessAuthService
#  data:
#    redis:
#      host: localhost
#      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 16032005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username:  ************
    password: *********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  task:
    execution:
      thread-name-prefix: async-task-
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 10

# JWT Access Token Settings
jwt:
  secret: ********************
  expiration:
    ms: 300000

  # Refresh Token Settings
  refresh-expiration:
    ms: 604800000

# OTP Settings
otp:
  expiration-seconds: 180


logging:
  level:
    com.example.businessauthService: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# SpringDoc OpenAPI (Swagger UI) Konfiqurasiyas?
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

server:
  port: 9191

